import { Inter } from "@next/font/google";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Home page</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<nav>
					<Link href="about">About</Link>
					<Link href="blog">Blog</Link>
				</nav>
				<h1>This is home page</h1>
				<Image src="/cat.jpg" width={600} height={400} />
			</main>
		</>
	);
}
